export const legacyDestinations = [
  ["Bản đồ", "/map", "all"],
  ["Giám sát hình ảnh", "/image-monitor", "FUNC_GIAMSAT_HT"],
  ["Giám sát camera", "/video-monitor", "FUNC_GIAMSAT_CAMERA"],
  ["Tìm kiếm vi phạm", "/violation", "FUNC_TEC_TIMKIEM_VP"],
  ["Truy vết đối tượng", "/nvaevents", "FUNC_TEC_TRUYVET"],
  ["Nhận diện khuôn mặt", "/face-recognition", "FUNC_NHANDIEN_KM"],
  ["Nút giao thông", "/trafficnode", "FUNC_LAN_SONG_XANH"],
  ["Tuyến làn sóng xanh", "/greenwave", "FUNC_NUT_GIAO_THONG"],
  ["Trạm dừng", "/stop-station", "FUNC_TRAM_DUNG"],
  ["Quản lý hạ tầng", "/infrastructure", "FUNC_QL_HA_TANG"],
  ["Tuyến số", "/bus-route", "FUNC_TUYEN_XE"],
  ["Cấu hình bảng điện tử", "/electronic-board", "FUNC_CAU_HINH_BDT"],
  ["Lịch trình", "/schedule", "FUNC_LICH_TRINH"],
  ["Đối tượng gán thiết bị", "/vehicle", "FUNC_OBJECT"],
  ["Lái xe", "/drive", "FUNC_LAIXE"],
  ["Báo cáo", "/statistic", "FUNC_BAO_CAO"],
  ["Chia sẻ dữ liệu", "/datasharing", "FUNC_CHIA_SE"],
  ["Lịch sử", "/history", "FUNC_TMMS_LS"],
  ["Loại thiết bị", "/devicetype", "FUNC_DEVICE_TYPE"],
  ["Thiết bị", "/device", "FUNC_THIET_BI"],
  ["Cấu hình bảng điện tử", "/electronic-board", "FUNC_CAU_HINH_BDT"],
  ["Biểu tượng", "/icon", "FUNC_BIEU_TUONG"],
  ["Màu sắc", "/color", "FUNC_MAU"],
  ["Loại hình vận tải", "/transporttype", "FUNC_LOAI_HINH_VAN_TAI"],
  ["Loại phương tiện", "/vehicletype", "FUNC_LOAI_PHUONG_TIEN"],
  ["Tuyến đường", "/management-route", "FUNC_TUYEN_DUONG"],
  ["Người sử dụng", "/decentralization", "FUNC_NGUOI_SU_DUNG"],
  ["Tổ chức", "/organization", "FUNC_TO_CHUC"],
  ["Gói dự án", "/project-package", "FUNC_GOI_DUAN"],
  ["Loại cảnh báo", "/alert-type", "FUNC_ALERT_TYPE"],
  ["Thông báo", "/notification", "FUNC_THONG_BAO"],
  ["Tin tức", "/news", "FUNC_BAIBAO"],
  ["Phản hồi", "/feedback", "FUNC_PHAN_HOI"],
  ["Quản lý danh sách kiểm soát", "/whitelist", "FUNC_DS_KIEM_SOAT"],
] as const;
